### ISSUE TITLE
"closeOnClickOutside" has stopped working

### ISSUE THREAD

**Issue by elega9t** [arkon/ng-sidebar#91] opened 2017-06-08 18:55 UTC
I recently upgraded the version to 5.0.2. After the upgrade, I noticed that sidebar is no longer getting closed on mouse click outside.

**Comment by arkon** [comment] 2017-06-08 19:26
Are you using `[closeOnClickOutside]`? It works fine in the demo.

**Comment by elega9t** [comment] 2017-06-09 07:53
Hi, yes, the declaration looks like

<ng-sidebar [(opened)]="appMenuVisible" sidebarClass="ui-widget-header" mode="slide" closeOnClickOutside=true>

I have tried changing it to

<ng-sidebar [(opened)]="appMenuVisible" sidebarClass="ui-widget-header" mode="slide" [closeOnClickOutside]=true>

but it still does not work.

It used to work with my previous version 4.2.3. I have recently updated a few dependency versions including ng-sidebar.

"@types/systemjs": "^0.19.31" => "^0.20.2"
"systemjs-builder": "0.15.34" => "0.16.4"
"ng-sidebar": "^4.2.3" => "^5.0.2"
"systemjs": "0.19.41" => "0.20.12"

If the issue is not obvious, I can try and reproduce the issue in a sample app and share it with you.

Thanks for sharing a great component.

**Comment by arkon** [comment] 2017-06-09 16:51
Unfortunately, the issue isn't obvious. :(

A sample would be great!

**Comment by arkon** [comment] 2017-06-09 19:29
@elega9t Actually, it seems like it _is_ broken for slide mode specifically. I'll take a look at it.

**Comment by elega9t** [comment] 2017-06-09 20:50
Thanks for an update. I suspect you were able to reproduce it?

**Comment by arkon** [comment] 2017-06-09 20:52
@elega9t Yeah. I'll push out a fix later today.

**Comment by arkon** [comment] 2017-06-09 23:01
Fixed in v5.0.4.

**Closed by arkon** 2017-06-09 23:01 UTC
Labels: bug
