### ISSUE TITLE
Sidebar coming out of a <div> edge?

### ISSUE THREAD

**Issue by amitm02** [arkon/ng-sidebar#83] opened 2017-05-30 09:00 UTC
Is it possible to put the sidebar inside a <div></div> element so it will not come out from the screen edge but instead from the <div> edge?

Reason is that i don't want the sidebar to cover my top menu...

**Comment by arkon** [comment] 2017-05-30 14:46
Duplicate of #51

**Closed by arkon** 2017-05-30 14:46 UTC
